version: '3.9'

networks:
  service_network:
    external: false

services:
  # http://localhost:8080/
  # http://localhost:8001/
  kong:
    image: heitorcarneiro/docker-kong-oidc:3.3.0-1-alpine
    container_name: kong_gateway
    environment:
      # KONG_DATABASE: 'off'
      # KONG_PROXY_LISTEN: '0.0.0.0:8080'
      # KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      # KONG_STATUS_LISTEN: '0.0.0.0:8100'
      # KONG_ADMIN_ACCESS_LOG: 'off'
      # KONG_ADMIN_ERROR_LOG: /dev/stderr
      # KONG_PROXY_ACCESS_LOG: 'off'
      # KONG_PROXY_ERROR_LOG: /dev/stderr
      # KONG_ANONYMOUS_REPORTS: false
      # KONG_DECLARATIVE_CONFIG: '/opt/kong/kong.yaml'
      KONG_PLUGINS: bundled,oidc,domain-restriction
      KONG_LOG_LEVEL: info
      KONG_X_SESSION_NAME: _atendimento_session
      KONG_X_SESSION_COMPRESSOR: zlib
    ports:
      - '8080:8080'
      - '8001:8001'
      - '8100:8100'
    networks:
      - service_network
    healthcheck:
      test: ['CMD', 'kong', 'health']
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - './kong.yaml:/opt/kong/kong.yaml:rw'
