version: '3'

vars:
  BIN_DIR: '{{.USER_WORKING_DIR}}/bin'

dotenv: ['.env']

tasks:
  download:
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - curl -L https://github.com/hguerra/envsubst/releases/download/v1.0.6/envsubst_linux_amd64 -o ./bin/envsubst && chmod +x ./bin/envsubst

  clean:
    cmds:
      - rm -rf kong.yaml

  config:
    cmds:
      - bin/envsubst -no-empty < configs/kong-template.yaml > kong.yaml

  build:
    cmds:
      - task: clean
      - task: config
      - docker build -t heitorcarneiro/kong:3.3.0-ubuntu .

  up:
    cmds:
      - docker compose up -d
      - docker compose logs -f kong

  down:
    cmds:
      - docker compose down

  run:
    cmds:
      - task: down
      - task: build
      - task: up

  test:
    cmds:
      - curl -i --location --request GET "http://localhost:8080"

  test_auth:
    cmds:
      - curl -i --location --request GET "http://localhost:8080" --header "my_header_key:test"
